In [1]:
import numpy

In [2]:
n = numpy.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
type(n)

numpy.ndarray

In [6]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [12]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [13]:
type(n.reshape(3,9))

numpy.ndarray

In [8]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
m = numpy.asarray([[123, 12, 123, 33], [], []])

In [10]:
m

array([[123, 12, 123, 33], [], []], dtype=object)

In [11]:
print(m)

[[123, 12, 123, 33] [] []]


In [15]:
type(m)

numpy.ndarray

In [14]:
import cv2

In [27]:
im_g = cv2.imread("smallgray.png", 0)
im_g
#reading in gray scale

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [26]:
im_g_bgr = cv2.imread("smallgray.png", 1)
im_g_bgr
#reading in bgr

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [28]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [30]:
cv2.imwrite("newsmallgray_bgr.png", im_g_bgr)

True

In [32]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [35]:
im_g[:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [37]:
im_g[:, 1]

array([158, 125, 134], dtype=uint8)

In [39]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [41]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [43]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [47]:
ims = numpy.hstack((im_g, im_g)) #concatnating two numpy arrays

In [48]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [50]:
imv = numpy.vstack((im_g, im_g))
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [54]:
cv2.imwrite("double image.png", im_g)

True

In [57]:
lst = numpy.hsplit(ims, 5)
lst

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8), array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8), array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8), array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8), array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]

In [61]:
sp = cv2.imread("superman.jpg", 1)
print(sp)

[[[0 1 2]
  [0 1 2]
  [0 0 4]
  ..., 
  [2 0 0]
  [4 0 0]
  [4 0 0]]

 [[0 1 2]
  [0 1 2]
  [0 0 4]
  ..., 
  [2 0 0]
  [4 0 0]
  [4 0 0]]

 [[0 1 2]
  [0 1 2]
  [0 0 4]
  ..., 
  [2 0 0]
  [4 0 0]
  [4 0 0]]

 ..., 
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [1 1 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [3 1 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [3 1 1]]]


In [63]:
cv2.imwrite("sp.jpg", sp)

True

In [67]:
with open('sp.txt', 'w') as file:
    file.write(str(sp))